# --- Typography ---
font_size        20.0

# Disable anti-aliasing / smoothing to keep individual text pixels sharp
disable_ligatures never

# --- The Workspace Palette ---
background            #1c1c1c
foreground            #f5f5dc
selection_background  #f5f5dc
selection_foreground  #1c1c1c

# Window border colors inside kitty frame
active_border_color   #f5f5dc
inactive_border_color #2a2a2a

# --- Instant Window Closure Hook ---
# This forces Kitty to immediately shut down when Hyprland triggers a kill active event
# instead of leaving zombie processes behind.
confirm_os_window_close 0

clipboard_control write-clipboard write-primary read-clipboard read-primary


# BEGIN_KITTY_FONTS
font_family      family=scientifica postscript_name=scientifica
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

map ctrl+shift+left no_op
map ctrl+shift+right no_op
