#TODO change according to your monitor setup

# 1. Preload the asset once into graphics memory
#TODO change to your user's Pictures path 
preload = /home/.../Pictures/wallpapers/13.png

# 2. Assign to your primary landscape monitor
wallpaper {
    monitor = DP-2
    #TODO change to your user's Pictures path 
    path = /home/.../Pictures/wallpapers/13.png
    fit_mode = fit
}

# 3. Assign to your secondary vertical monitor
wallpaper {
    monitor = HDMI-A-1
    #TODO change to your user's Pictures path 
    path = /home/.../Pictures/wallpapers/13.png
    fit_mode = fit
}

# Optional: Turn off the default anime mascot text rendering on top
splash = false
